### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by aqua-lzma** [aqua-lzma/coffeedrop#3]
- [ ] - Blur shader
  - [ ] - Remake Tensei
- [x] - Remake vector trails
- [ ] - Github pages builds
  - [ ] - Build from tags
  - [ ] - Catalogue
- [ ] - Perlin scalars as a texture
- [ ] - Figure out correct magnitude for perlin gradients
- [ ] - Configurable textures on `initBuffer`
